<?php
namespace App\Repository;

use App\Entity\Member;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * @extends ServiceEntityRepository<Member>
 *
 * @method Member|null find($id, $lockMode = null, $lockVersion = null)
 * @method Member|null findOneBy(array $criteria, array $orderBy = null)
 * @method Member[]    findAll()
 * @method Member[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class MemberRepository extends BaseRepository
{
    public function getClass(): string
    {
        return Member::class; // TODO: Change the autogenerated stub
    }

    /**
     * Récupère tous les membres actifs du système.
     * * @return Member[]
     */
    public function findActiveMembers(): array
    {
        return $this->createQueryBuilder('m')
            ->andWhere('m.isActive = :active')
            ->setParameter('active', true)
            ->orderBy('m.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Récupère les membres dont le compte est temporairement suspendu ou bloqué.
     * * @return Member[]
     */
    public function findSuspendedMembers(): array
    {
        return $this->createQueryBuilder('m')
            ->andWhere('m.isActive = :active')
            ->setParameter('active', false)
            ->orderBy('m.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Recherche un membre par une correspondance partielle sur son nom ou son email.
     * Pratique pour les barres de recherche d'autocomplétion côté Frontend (ReactJS).
     * * @return Member[]
     */
    public function searchByKeyword(string $keyword): array
    {
        return $this->createQueryBuilder('m')
            ->andWhere('m.name LIKE :search OR m.email LIKE :search')
            ->setParameter('search', '%' . $keyword . '%')
            ->orderBy('m.name', 'ASC')
            ->setMaxResults(10) // Limite pour optimiser les performances réseau
            ->getQuery()
            ->getResult();
    }


}
