<?php
namespace App\Repository;

use App\Entity\Product;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * @extends ServiceEntityRepository<Product>
 */
class ProductRepository extends BaseRepository
{
    public function getClass(): string
    {
        return Product::class; // TODO: Change the autogenerated stub
    }

    /**
     * Finds all products that are running low on stock.
     * Useful for triggering "reorder" alerts.
     * * @return Product[]
     */
    public function findLowStockProducts(int $threshold = 10): array
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.currentStock <= :threshold')
            ->setParameter('threshold', $threshold)
            ->orderBy('p.currentStock', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Finds all products that are completely out of stock.
     * * @return Product[]
     */
    public function findOutOfStockProducts(): array
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.currentStock = 0')
            ->orderBy('p.name', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
