<?php

namespace App\Repository;

use App\Entity\Product;
use App\Entity\StockMovement;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * @extends ServiceEntityRepository<StockMovement>
 */
class StockMovementRepository extends BaseRepository
{

    public function getClass(): string
    {
        return StockMovement::class; // TODO: Change the autogenerated stub
    }

    /**
     * Get the movement history for a specific product, ordered by latest first.
     * * @return StockMovement[]
     */
    public function findHistoryByProduct(Product $product, int $limit = 50): array
    {
        return $this->createQueryBuilder('sm')
            ->andWhere('sm.product = :product')
            ->setParameter('product', $product)
            ->orderBy('sm.createdAt', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * Summarize stock changes for a specific period.
     * Great for sending daily or weekly inventory reports to n8n.
     * * @return StockMovement[]
     */
    public function findMovementsInTimeframe(\DateTimeInterface $start, \DateTimeInterface $end): array
    {
        return $this->createQueryBuilder('sm')
            ->andWhere('sm.createdAt >= :start')
            ->andWhere('sm.createdAt <= :end')
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->orderBy('sm.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
